server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/insurance_db}
    username: ${SPRING_DATASOURCE_USERNAME:insurance_user}
    password: ${SPRING_DATASOURCE_PASSWORD:insurance_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
